config/routes.rb
VersativeMongo::Application.routes.draw do

  
  resources :projects
  resources :users
  resources :custom_fields
  resources :work_item_types
  resources :documents
  resources :work_items do
    resources :comments
  end
  
  root :to => 'users#index'
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning

  field :text, type: String

  embedded_in :work_item
  
  after_save :print_message
  
  def print_message
    p "Comment was created"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_work_item
  # GET /comments
  # GET /comments.json
  def index
    @comments = @work_item.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = @work_item.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = @work_item.comments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = @work_item.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @work_item.comments.build(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to work_item_comment_url(@work_item,@comment), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = @work_item.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to work_item_comment_url(@work_item,@comment), notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = @work_item.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to work_item_comments_url(@work_item) }
      format.json { head :ok }
    end
  end
  
  def find_work_item
    @work_item = WorkItem.find(params[:work_item_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= simple_form_for [@work_item,@comment] do |f|
  = f.error_notification

  .inputs
    = f.input :text

  .actions
    = f.button :submit, :class => 'btn primary'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Back', work_item_comments_path(@work_item)

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %tr
    %th Text
    %th
    %th
    %th

  - @comments.each do |comment|
    %tr
      %td= comment.text
      %td= link_to 'Show', work_item_comment_path(comment.id, :work_item_id => @work_item.id)
      %td= link_to 'Edit', edit_work_item_comment_path(comment.id, :work_item_id => @work_item.id)
      %td= link_to 'Destroy', work_item_comment_path(comment.id, :work_item_id => @work_item.id), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Comment', new_work_item_comment_path(@work_item)

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', work_item_comments_path(@work_item)

app/views/comments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_work_item_comment_path(@work_item, @comment)
\|
= link_to 'Back', work_item_comments_path(@work_item)