config/routes.rb
VersativeMongo::Application.routes.draw do

  
  resources :projects
  resources :users
  resources :custom_fields
  resources :work_item_types
  resources :documents
  resources :work_items do
    resources :comments
  end
  
  root :to => 'users#index'
end

app/models/work_item.rb
class WorkItem
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Tree
  include Tenacity
  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  field :name, type: String
  
  t_belongs_to  :user
  belongs_to    :work_item_type
  belongs_to    :project
  embeds_many   :comments
  has_many      :outgoings, :class_name => 'WorkItemRelation', :foreign_key => 'incoming_id'
  has_many      :incomings, :class_name => 'WorkItemRelation', :foreign_key => 'outgoing_id'
  has_and_belongs_to_many :documents
  
  validates_presence_of   :work_item_type

  shard_key :project_id

end

app/models/work_item_type.rb
class WorkItemType
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String
  
  has_and_belongs_to_many :custom_fields
  has_many :work_items

  validates_presence_of   :name
  
  def to_s
    name
  end
  
end

app/controllers/work_items_controller.rb
class WorkItemsController < ApplicationController
  # GET /work_items
  # GET /work_items.json
  def index
    @work_items = if params[:q]
      WorkItem.tire.search(params[:q], :load => true, :page => params[:page] || 1, :per_page => Kaminari.config.default_per_page)
    else
      WorkItem.page(params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_items }
    end
  end

  # GET /work_items/1
  # GET /work_items/1.json
  def show
    @work_item = WorkItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_item }
      format.rdf
    end
  end

  # GET /work_items/new
  # GET /work_items/new.json
  def new
    @work_item = WorkItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_item }
    end
  end

  # GET /work_items/1/edit
  def edit
    @work_item = WorkItem.find(params[:id])
  end

  # POST /work_items
  # POST /work_items.json
  def create
    @work_item = WorkItem.new(params[:work_item])

    respond_to do |format|
      if @work_item.save
        format.html { redirect_to @work_item, notice: 'Work item was successfully created.' }
        format.json { render json: @work_item, status: :created, location: @work_item }
      else
        format.html { render action: "new" }
        format.json { render json: @work_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_items/1
  # PUT /work_items/1.json
  def update
    @work_item = WorkItem.find(params[:id])

    respond_to do |format|
      if @work_item.update_attributes(params[:work_item])
        format.html { redirect_to @work_item, notice: 'Work item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @work_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_items/1
  # DELETE /work_items/1.json
  def destroy
    @work_item = WorkItem.find(params[:id])
    @work_item.destroy

    respond_to do |format|
      format.html { redirect_to work_items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/work_items_helper.rb
module WorkItemsHelper
end

app/views/work_items/_form.html.haml
= simple_form_for(@work_item) do |f|
  = f.error_notification

  .inputs
    = f.input :name
    = f.input :user_id, :collection => User.all, :include_blank => false
    - if @work_item.new_record?
      = f.input :project, :collection => Project.all, :include_blank => false
      = f.input :work_item_type, :collection => WorkItemType.all, :include_blank => false
    - else
      - @work_item.work_item_type.custom_fields.to_a.each do |custom_field|
        .input
          = label_tag "work_item[#{custom_field.name}]", custom_field.name
          - if custom_field.type == 'option'
            = select_tag "work_item[#{custom_field.name}]", options_for_select(custom_field.values)
          - else
            = text_field_tag "work_item[#{custom_field.name}]", @work_item[custom_field.name]

  .actions
    = f.button :submit, :class => "btn primary"

app/views/work_items/edit.html.haml
%h1 Editing work_item

= render 'form'

= link_to 'Show', @work_item
\|
= link_to 'Back', work_items_path

app/views/work_items/index.html.haml
%h1 Listing work_items

= form_tag work_items_path, :method => :get do
  = text_field_tag :q, params[:q]
  = submit_tag "Search", :class => "btn primary"
  - if params[:q]
    = link_to "Clear", work_items_path, :class => "btn"

%table.zebra-striped
  %thead
    %tr
      %th Name
      %th User
      %th Work item type
      %th
      %th
      %th
      %th
  %tbody
    - @work_items.each do |work_item|
      %tr
        %td= work_item.name
        %td= work_item.user
        %td= work_item.work_item_type
        %td
          = work_item.comments.size
          = link_to 'Comments', work_item_comments_path(work_item)
        %td= link_to 'Show', work_item
        %td= link_to 'Edit', edit_work_item_path(work_item)
        %td= link_to 'Destroy', work_item, :confirm => 'Are you sure?', :method => :delete

= paginate @work_items

%br

= link_to 'New Work item', new_work_item_path

app/views/work_items/new.html.haml
%h1 New work_item

= render 'form'

= link_to 'Back', work_items_path

app/views/work_items/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_work_item_path(@work_item)
\|
= link_to 'Back', work_items_path