config/routes.rb
VersativeMongo::Application.routes.draw do

  
  resources :projects
  resources :users
  resources :custom_fields
  resources :work_item_types
  resources :documents
  resources :work_items do
    resources :comments
  end
  
  root :to => 'users#index'
end

app/models/document.rb
class Document
  include Mongoid::Document
  
  field :name, type: String
  key :name do
    Document.count + 1
  end
  
  has_and_belongs_to_many :work_items

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.haml
= simple_form_for(@document) do |f|
  = f.error_notification

  .inputs
    = f.input :name

  .actions
    = f.button :submit, :class => 'btn primary'

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%h1 Listing documents

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @documents.each do |document|
    %tr
      %td= document.name
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Document', new_document_path

app/views/documents/new.html.haml
%h1 New document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path