config/routes.rb
VersativeMongo::Application.routes.draw do

  
  resources :projects
  resources :users
  resources :custom_fields
  resources :work_item_types
  resources :documents
  resources :work_items do
    resources :comments
  end
  
  root :to => 'users#index'
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  has_many :work_items
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .inputs
    = f.input :name

  .actions
    = f.button :submit, :class => 'btn primary'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path